spring.application.name: demo

springdoc.api-docs.path: "/api-docs"

spring.datasource:
  url: jdbc:postgresql://localhost:5432/wrc
  username: admin
  password: admin
  driver-class-name: org.postgresql.Driver


